# Generated by Django 5.0.6 on 2024-10-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_customuser_pub_date_alter_customuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_message_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
