# Generated by Django 5.0.6 on 2024-11-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_message_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_message_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
